### ISSUE TITLE
ImportError: No module named yapps

### ISSUE THREAD

**Issue by SujungBae** [bowenbaker/metaqnn#4]
When I run 
> python q_server.py cifar10 cifar10_logs

Following error occurs
Traceback (most recent call last):
  File "q_server.py", line 4, in <module>
    import libs.grammar.q_protocol as q_protocol
  File "/metaqnn-master/libs/grammar/__init__.py", line 1, in <module>
    import q_learner
  File "/metaqnn-master/libs/grammar/q_learner.py", line 6, in <module>
    import cnn
  File "/metaqnn-master/libs/grammar/cnn.py", line 4, in <module>
    from yapps import runtime
ImportError: No module named yapps

What is the 'yapps'?
How can I solve it?

**Comment by SujungBae** [comment]
I found the yapps (https://github.com/smurfix/yapps)
I will leave my previous issue for other users.
